name: Setup Nix
description: Setup Nix with caching
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        diagnostic-endpoint: ""
        summarize: false
        extra-conf: |
          always-allow-substitutes = false
          http-connections = 0
          keep-going = true
          narinfo-cache-negative-ttl = 0
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        diff-store: true
        diagnostic-endpoint: ""
    - uses: actions/cache@main
      with:
        path: ~/.cache/nix
        key: nix-cache-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        restore-keys: nix-cache-${{ runner.os }}-${{ runner.arch }}-
