name: Setup Nix
description: Setup Nix with caching
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        diagnostic-endpoint: ""
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        diff-store: true
        diagnostic-endpoint: ""
    - uses: actions/cache@main
      with:
        path: ~/.cache/nix
        key: ${{ runner.os }}-nix-cache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-nix-cache-
